name: Publish Release

on:
    push:
        tags:
            - '*'

permissions:
    contents: write

jobs:
    release-free:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Install dependencies
              run: npm install --force

            - name: Build
              run: npm run build

            - name: Create swift-checkout directory and move files
              run: |
                mkdir -p swift-checkout &&
                find . -maxdepth 1 -not -name 'swift-checkout' -exec mv {} swift-checkout \;

            - name: Archive release
              uses: thedoctor0/zip-release@0.7.6
              with:
                filename: 'swift-checkout.zip'
                exclusions: >-
                  /*sync.ffs_db /*.idea/* /*.DS_Store /*.gitignore /*.github/* /*.git/* /*.cursorrules /*.eslintrc /*.gitattributes /*.prettierrc
                  /*composer.lock /includes/assets/* /*.sublime-project /*.sublime-workspace /*.DS_Store? /*._* /*.Spotlight-V100 /*.Trashes
                  /*ehthumbs.db /*Thumbs.db /build/* /node_modules/* /*package-lock.json /*pnpm-lock.yaml /*.env /*.env.* /*.log /*npm-debug.log*
                  /*yarn-debug.log* /*yarn-error.log* /.cache/* /.temp/* /coverage/* /build/Release/* /.npm/* /.eslintcache/* /*.tgz /*.zip

            - name: Display release
              run: ls -a

            - name: Create Release
              uses: ncipollo/release-action@v1.14.0
              with:
                artifacts: './swift-checkout.zip'
                token: ${{ secrets.TOKEN }}
                removeArtifacts: true
                allowUpdates: true
                makeLatest: true
                tag: ${{ github.ref_name }}